spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/kkurukkuru
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
kakao:
  client-id: 840a2bdb9d990844770a7bca682d1f59
  client-secret: L5uwEimfLfzDbUWMXl70WP53deKBsGVT
  redirect-uri: http://localhost:5173/callback

jwt:
  secret: ijjfj0s9fdj90sjiofjaiosdfjioasjfoiasjdfiosjadfiojsadiofjasiodfjsadiofjadsiofjiosadfjiojfipejaoipfjaiopjfiopasjfiosdjaiofpajsdf
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 2592000000  # 30일